// apps/storefront-vite-vue3-antd/bootstrap/App.vue
<template>
  <nav>
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </nav>
  <ConfigProvider :prefix-cls="prefixCls">
    <Header />
  </ConfigProvider>
</template>

<script>
import { defineComponent, ref } from 'vue'
import { ConfigProvider } from '@headless/vue3-antd'

import Header from '@components/Header'

export default defineComponent({
  name: 'App',
  components: {
    ConfigProvider,
    Header
  },
  setup() {
    const prefixCls = ref(null)

    prefixCls.value = 'headless'

    return {
      prefixCls
    }
  }
})
</script>

// apps/storefront-create-react-app-antd/src/App.js
import { BrowserRouter } from 'react-router-dom'

import { ConfigProvider } from '@headless/react-antd'
import { ThemeConf } from '@config/theme.conf'

import Header from '@components/Header'

const App = () => {
  return (
    <BrowserRouter>
      <ConfigProvider prefixCls={ThemeConf.prefix}>
        <Header />
      </ConfigProvider>
    </BrowserRouter>
  )
}

export default App
